# Generated by Django 6.0.4 on 2026-04-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('git', models.URLField(max_length=400)),
                ('linkedin', models.URLField(max_length=400)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
    ]
