# Generated by Django 6.0.4 on 2026-04-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projeto_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetificado',
            new_name='Certificado',
        ),
    ]
